// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk.Protocol.Java;

namespace Umpk.Data.Java;

/// <summary>Generated version catalog. Implements the IVersionCatalog seam.</summary>
/// <remarks>Trimming-load-bearing shape (normative): no static constructor and no static field initializers. Every V* property lazily constructs through its own backing field so the trimmer can drop unreferenced versions. All and TryGetBy* obey the same rule: lazy bodies, no static initializers, so touching one V* property never roots the whole catalog.</remarks>
public static class JavaVersions
{
    /// <summary>1.8 (protocol 47).</summary>
    public static JavaVersion V1_8 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();
    private static JavaVersion? s_v47;

    /// <summary>1.8.1 (protocol 47).</summary>
    public static JavaVersion V1_8_1 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.2 (protocol 47).</summary>
    public static JavaVersion V1_8_2 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.3 (protocol 47).</summary>
    public static JavaVersion V1_8_3 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.4 (protocol 47).</summary>
    public static JavaVersion V1_8_4 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.5 (protocol 47).</summary>
    public static JavaVersion V1_8_5 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.6 (protocol 47).</summary>
    public static JavaVersion V1_8_6 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.7 (protocol 47).</summary>
    public static JavaVersion V1_8_7 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.8 (protocol 47).</summary>
    public static JavaVersion V1_8_8 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.8.9 (protocol 47).</summary>
    public static JavaVersion V1_8_9 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();

    /// <summary>1.9 (protocol 107).</summary>
    public static JavaVersion V1_9 => s_v107 ??= global::Umpk.Data.Java.V107.Descriptor.Build();
    private static JavaVersion? s_v107;

    /// <summary>1.9.1 (protocol 108).</summary>
    public static JavaVersion V1_9_1 => s_v108 ??= global::Umpk.Data.Java.V108.Descriptor.Build();
    private static JavaVersion? s_v108;

    /// <summary>1.9.2 (protocol 109).</summary>
    public static JavaVersion V1_9_2 => s_v109 ??= global::Umpk.Data.Java.V109.Descriptor.Build();
    private static JavaVersion? s_v109;

    /// <summary>1.9.3 (protocol 110).</summary>
    public static JavaVersion V1_9_3 => s_v110 ??= global::Umpk.Data.Java.V110.Descriptor.Build();
    private static JavaVersion? s_v110;

    /// <summary>1.9.4 (protocol 110).</summary>
    public static JavaVersion V1_9_4 => s_v110 ??= global::Umpk.Data.Java.V110.Descriptor.Build();

    /// <summary>1.10 (protocol 210).</summary>
    public static JavaVersion V1_10 => s_v210 ??= global::Umpk.Data.Java.V210.Descriptor.Build();
    private static JavaVersion? s_v210;

    /// <summary>1.10.1 (protocol 210).</summary>
    public static JavaVersion V1_10_1 => s_v210 ??= global::Umpk.Data.Java.V210.Descriptor.Build();

    /// <summary>1.10.2 (protocol 210).</summary>
    public static JavaVersion V1_10_2 => s_v210 ??= global::Umpk.Data.Java.V210.Descriptor.Build();

    /// <summary>1.11 (protocol 315).</summary>
    public static JavaVersion V1_11 => s_v315 ??= global::Umpk.Data.Java.V315.Descriptor.Build();
    private static JavaVersion? s_v315;

    /// <summary>1.11.1 (protocol 316).</summary>
    public static JavaVersion V1_11_1 => s_v316 ??= global::Umpk.Data.Java.V316.Descriptor.Build();
    private static JavaVersion? s_v316;

    /// <summary>1.11.2 (protocol 316).</summary>
    public static JavaVersion V1_11_2 => s_v316 ??= global::Umpk.Data.Java.V316.Descriptor.Build();

    /// <summary>1.12 (protocol 335).</summary>
    public static JavaVersion V1_12 => s_v335 ??= global::Umpk.Data.Java.V335.Descriptor.Build();
    private static JavaVersion? s_v335;

    /// <summary>1.12.1 (protocol 338).</summary>
    public static JavaVersion V1_12_1 => s_v338 ??= global::Umpk.Data.Java.V338.Descriptor.Build();
    private static JavaVersion? s_v338;

    /// <summary>1.12.2 (protocol 340).</summary>
    public static JavaVersion V1_12_2 => s_v340 ??= global::Umpk.Data.Java.V340.Descriptor.Build();
    private static JavaVersion? s_v340;

    /// <summary>1.13 (protocol 393).</summary>
    public static JavaVersion V1_13 => s_v393 ??= global::Umpk.Data.Java.V393.Descriptor.Build();
    private static JavaVersion? s_v393;

    /// <summary>1.13.1 (protocol 401).</summary>
    public static JavaVersion V1_13_1 => s_v401 ??= global::Umpk.Data.Java.V401.Descriptor.Build();
    private static JavaVersion? s_v401;

    /// <summary>1.13.2 (protocol 404).</summary>
    public static JavaVersion V1_13_2 => s_v404 ??= global::Umpk.Data.Java.V404.Descriptor.Build();
    private static JavaVersion? s_v404;

    /// <summary>1.14 (protocol 477).</summary>
    public static JavaVersion V1_14 => s_v477 ??= global::Umpk.Data.Java.V477.Descriptor.Build();
    private static JavaVersion? s_v477;

    /// <summary>1.14.1 (protocol 480).</summary>
    public static JavaVersion V1_14_1 => s_v480 ??= global::Umpk.Data.Java.V480.Descriptor.Build();
    private static JavaVersion? s_v480;

    /// <summary>1.14.2 (protocol 485).</summary>
    public static JavaVersion V1_14_2 => s_v485 ??= global::Umpk.Data.Java.V485.Descriptor.Build();
    private static JavaVersion? s_v485;

    /// <summary>1.14.3 (protocol 490).</summary>
    public static JavaVersion V1_14_3 => s_v490 ??= global::Umpk.Data.Java.V490.Descriptor.Build();
    private static JavaVersion? s_v490;

    /// <summary>1.14.4 (protocol 498).</summary>
    public static JavaVersion V1_14_4 => s_v498 ??= global::Umpk.Data.Java.V498.Descriptor.Build();
    private static JavaVersion? s_v498;

    /// <summary>1.15 (protocol 573).</summary>
    public static JavaVersion V1_15 => s_v573 ??= global::Umpk.Data.Java.V573.Descriptor.Build();
    private static JavaVersion? s_v573;

    /// <summary>1.15.1 (protocol 575).</summary>
    public static JavaVersion V1_15_1 => s_v575 ??= global::Umpk.Data.Java.V575.Descriptor.Build();
    private static JavaVersion? s_v575;

    /// <summary>1.15.2 (protocol 578).</summary>
    public static JavaVersion V1_15_2 => s_v578 ??= global::Umpk.Data.Java.V578.Descriptor.Build();
    private static JavaVersion? s_v578;

    /// <summary>1.16 (protocol 735).</summary>
    public static JavaVersion V1_16 => s_v735 ??= global::Umpk.Data.Java.V735.Descriptor.Build();
    private static JavaVersion? s_v735;

    /// <summary>1.16.1 (protocol 736).</summary>
    public static JavaVersion V1_16_1 => s_v736 ??= global::Umpk.Data.Java.V736.Descriptor.Build();
    private static JavaVersion? s_v736;

    /// <summary>1.16.2 (protocol 751).</summary>
    public static JavaVersion V1_16_2 => s_v751 ??= global::Umpk.Data.Java.V751.Descriptor.Build();
    private static JavaVersion? s_v751;

    /// <summary>1.16.3 (protocol 753).</summary>
    public static JavaVersion V1_16_3 => s_v753 ??= global::Umpk.Data.Java.V753.Descriptor.Build();
    private static JavaVersion? s_v753;

    /// <summary>1.16.4 (protocol 754).</summary>
    public static JavaVersion V1_16_4 => s_v754 ??= global::Umpk.Data.Java.V754.Descriptor.Build();
    private static JavaVersion? s_v754;

    /// <summary>1.16.5 (protocol 754).</summary>
    public static JavaVersion V1_16_5 => s_v754 ??= global::Umpk.Data.Java.V754.Descriptor.Build();

    /// <summary>1.17 (protocol 755).</summary>
    public static JavaVersion V1_17 => s_v755 ??= global::Umpk.Data.Java.V755.Descriptor.Build();
    private static JavaVersion? s_v755;

    /// <summary>1.17.1 (protocol 756).</summary>
    public static JavaVersion V1_17_1 => s_v756 ??= global::Umpk.Data.Java.V756.Descriptor.Build();
    private static JavaVersion? s_v756;

    /// <summary>1.18 (protocol 757).</summary>
    public static JavaVersion V1_18 => s_v757 ??= global::Umpk.Data.Java.V757.Descriptor.Build();
    private static JavaVersion? s_v757;

    /// <summary>1.18.1 (protocol 757).</summary>
    public static JavaVersion V1_18_1 => s_v757 ??= global::Umpk.Data.Java.V757.Descriptor.Build();

    /// <summary>1.18.2 (protocol 758).</summary>
    public static JavaVersion V1_18_2 => s_v758 ??= global::Umpk.Data.Java.V758.Descriptor.Build();
    private static JavaVersion? s_v758;

    /// <summary>1.19 (protocol 759).</summary>
    public static JavaVersion V1_19 => s_v759 ??= global::Umpk.Data.Java.V759.Descriptor.Build();
    private static JavaVersion? s_v759;

    /// <summary>1.19.1 (protocol 760).</summary>
    public static JavaVersion V1_19_1 => s_v760 ??= global::Umpk.Data.Java.V760.Descriptor.Build();
    private static JavaVersion? s_v760;

    /// <summary>1.19.2 (protocol 760).</summary>
    public static JavaVersion V1_19_2 => s_v760 ??= global::Umpk.Data.Java.V760.Descriptor.Build();

    /// <summary>1.19.3 (protocol 761).</summary>
    public static JavaVersion V1_19_3 => s_v761 ??= global::Umpk.Data.Java.V761.Descriptor.Build();
    private static JavaVersion? s_v761;

    /// <summary>1.19.4 (protocol 762).</summary>
    public static JavaVersion V1_19_4 => s_v762 ??= global::Umpk.Data.Java.V762.Descriptor.Build();
    private static JavaVersion? s_v762;

    /// <summary>1.20 (protocol 763).</summary>
    public static JavaVersion V1_20 => s_v763 ??= global::Umpk.Data.Java.V763.Descriptor.Build();
    private static JavaVersion? s_v763;

    /// <summary>1.20.1 (protocol 763).</summary>
    public static JavaVersion V1_20_1 => s_v763 ??= global::Umpk.Data.Java.V763.Descriptor.Build();

    /// <summary>1.20.2 (protocol 764).</summary>
    public static JavaVersion V1_20_2 => s_v764 ??= global::Umpk.Data.Java.V764.Descriptor.Build();
    private static JavaVersion? s_v764;

    /// <summary>1.20.3 (protocol 765).</summary>
    public static JavaVersion V1_20_3 => s_v765 ??= global::Umpk.Data.Java.V765.Descriptor.Build();
    private static JavaVersion? s_v765;

    /// <summary>1.20.4 (protocol 765).</summary>
    public static JavaVersion V1_20_4 => s_v765 ??= global::Umpk.Data.Java.V765.Descriptor.Build();

    /// <summary>1.20.5 (protocol 766).</summary>
    public static JavaVersion V1_20_5 => s_v766 ??= global::Umpk.Data.Java.V766.Descriptor.Build();
    private static JavaVersion? s_v766;

    /// <summary>1.20.6 (protocol 766).</summary>
    public static JavaVersion V1_20_6 => s_v766 ??= global::Umpk.Data.Java.V766.Descriptor.Build();

    /// <summary>1.21 (protocol 767).</summary>
    public static JavaVersion V1_21 => s_v767 ??= global::Umpk.Data.Java.V767.Descriptor.Build();
    private static JavaVersion? s_v767;

    /// <summary>1.21.1 (protocol 767).</summary>
    public static JavaVersion V1_21_1 => s_v767 ??= global::Umpk.Data.Java.V767.Descriptor.Build();

    /// <summary>1.21.2 (protocol 768).</summary>
    public static JavaVersion V1_21_2 => s_v768 ??= global::Umpk.Data.Java.V768.Descriptor.Build();
    private static JavaVersion? s_v768;

    /// <summary>1.21.3 (protocol 768).</summary>
    public static JavaVersion V1_21_3 => s_v768 ??= global::Umpk.Data.Java.V768.Descriptor.Build();

    /// <summary>1.21.4 (protocol 769).</summary>
    public static JavaVersion V1_21_4 => s_v769 ??= global::Umpk.Data.Java.V769.Descriptor.Build();
    private static JavaVersion? s_v769;

    /// <summary>1.21.5 (protocol 770).</summary>
    public static JavaVersion V1_21_5 => s_v770 ??= global::Umpk.Data.Java.V770.Descriptor.Build();
    private static JavaVersion? s_v770;

    /// <summary>1.21.6 (protocol 771).</summary>
    public static JavaVersion V1_21_6 => s_v771 ??= global::Umpk.Data.Java.V771.Descriptor.Build();
    private static JavaVersion? s_v771;

    /// <summary>1.21.7 (protocol 772).</summary>
    public static JavaVersion V1_21_7 => s_v772 ??= global::Umpk.Data.Java.V772.Descriptor.Build();
    private static JavaVersion? s_v772;

    /// <summary>1.21.8 (protocol 772).</summary>
    public static JavaVersion V1_21_8 => s_v772 ??= global::Umpk.Data.Java.V772.Descriptor.Build();

    /// <summary>1.21.9 (protocol 773).</summary>
    public static JavaVersion V1_21_9 => s_v773 ??= global::Umpk.Data.Java.V773.Descriptor.Build();
    private static JavaVersion? s_v773;

    /// <summary>1.21.10 (protocol 773).</summary>
    public static JavaVersion V1_21_10 => s_v773 ??= global::Umpk.Data.Java.V773.Descriptor.Build();

    /// <summary>1.21.11 (protocol 774).</summary>
    public static JavaVersion V1_21_11 => s_v774 ??= global::Umpk.Data.Java.V774.Descriptor.Build();
    private static JavaVersion? s_v774;

    /// <summary>26.1 (protocol 775).</summary>
    public static JavaVersion V26_1 => s_v775 ??= global::Umpk.Data.Java.V775.Descriptor.Build();
    private static JavaVersion? s_v775;

    /// <summary>26.2 (protocol 776).</summary>
    public static JavaVersion V26_2 => s_v776 ??= global::Umpk.Data.Java.V776.Descriptor.Build();
    private static JavaVersion? s_v776;

    /// <summary>26.3 (protocol 777).</summary>
    public static JavaVersion V26_3 => s_v777 ??= global::Umpk.Data.Java.V777.Descriptor.Build();
    private static JavaVersion? s_v777;

    /// <summary>All supported versions. References every version and therefore roots the full data set.</summary>
    public static IReadOnlyList<JavaVersion> All => s_all ??= BuildAll();
    private static IReadOnlyList<JavaVersion>? s_all;

    private static IReadOnlyList<JavaVersion> BuildAll() =>
        new JavaVersion[] { V1_8, V1_9, V1_9_1, V1_9_2, V1_9_3, V1_10, V1_11, V1_11_1, V1_12, V1_12_1, V1_12_2, V1_13, V1_13_1, V1_13_2, V1_14, V1_14_1, V1_14_2, V1_14_3, V1_14_4, V1_15, V1_15_1, V1_15_2, V1_16, V1_16_1, V1_16_2, V1_16_3, V1_16_4, V1_17, V1_17_1, V1_18, V1_18_2, V1_19, V1_19_1, V1_19_3, V1_19_4, V1_20, V1_20_2, V1_20_3, V1_20_5, V1_21, V1_21_2, V1_21_4, V1_21_5, V1_21_6, V1_21_7, V1_21_9, V1_21_11, V26_1, V26_2, V26_3 };

    /// <summary>Look up a version by protocol number. Walks All lazily.</summary>
    public static bool TryGetByProtocol(int protocol, out JavaVersion version)
    {
        foreach (JavaVersion candidate in All)
        {
            if (candidate.Version.Protocol == protocol)
            {
                version = candidate;
                return true;
            }
        }
        version = default!;
        return false;
    }

    /// <summary>Look up a version by name ("1.21.5"). Resolves N:1 aliases ("1.20.3" and "1.20.4" both map to protocol 765) via the generated name table, which the single-name <c>JavaVersion.HasName</c> cannot express.</summary>
    public static bool TryGetByName(string name, out JavaVersion version)
    {
        int protocol = name switch
        {
            "1.8" => 47,
            "1.8.1" => 47,
            "1.8.2" => 47,
            "1.8.3" => 47,
            "1.8.4" => 47,
            "1.8.5" => 47,
            "1.8.6" => 47,
            "1.8.7" => 47,
            "1.8.8" => 47,
            "1.8.9" => 47,
            "1.9" => 107,
            "1.9.1" => 108,
            "1.9.2" => 109,
            "1.9.3" => 110,
            "1.9.4" => 110,
            "1.10" => 210,
            "1.10.1" => 210,
            "1.10.2" => 210,
            "1.11" => 315,
            "1.11.1" => 316,
            "1.11.2" => 316,
            "1.12" => 335,
            "1.12.1" => 338,
            "1.12.2" => 340,
            "1.13" => 393,
            "1.13.1" => 401,
            "1.13.2" => 404,
            "1.14" => 477,
            "1.14.1" => 480,
            "1.14.2" => 485,
            "1.14.3" => 490,
            "1.14.4" => 498,
            "1.15" => 573,
            "1.15.1" => 575,
            "1.15.2" => 578,
            "1.16" => 735,
            "1.16.1" => 736,
            "1.16.2" => 751,
            "1.16.3" => 753,
            "1.16.4" => 754,
            "1.16.5" => 754,
            "1.17" => 755,
            "1.17.1" => 756,
            "1.18" => 757,
            "1.18.1" => 757,
            "1.18.2" => 758,
            "1.19" => 759,
            "1.19.1" => 760,
            "1.19.2" => 760,
            "1.19.3" => 761,
            "1.19.4" => 762,
            "1.20" => 763,
            "1.20.1" => 763,
            "1.20.2" => 764,
            "1.20.3" => 765,
            "1.20.4" => 765,
            "1.20.5" => 766,
            "1.20.6" => 766,
            "1.21" => 767,
            "1.21.1" => 767,
            "1.21.2" => 768,
            "1.21.3" => 768,
            "1.21.4" => 769,
            "1.21.5" => 770,
            "1.21.6" => 771,
            "1.21.7" => 772,
            "1.21.8" => 772,
            "1.21.9" => 773,
            "1.21.10" => 773,
            "1.21.11" => 774,
            "26.1" => 775,
            "26.2" => 776,
            "26.3" => 777,
            _ => -1,
        };
        return protocol >= 0 && TryGetByProtocol(protocol, out version) || Fail(out version);
        static bool Fail(out JavaVersion v) { v = default!; return false; }
    }
}
