// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk.Game.Entities;

namespace Umpk.Data.Java;

/// <summary>The tier-2 metadata index tables, one per band of protocols that share a synched-data layout. Vanilla allocates an index per class in the order the <c>DATA_*</c> fields initialise, seeding from the nearest superclass's high-water mark, so a band boundary is exactly a protocol where <c>Entity</c> or <c>LivingEntity</c> gained a field. Each band's anchor is in its own <c>metadata-keys.json</c> provenance.</summary>
public sealed partial class JavaEntityMetadataKeys
{
    /// <summary>The era table for a protocol number. An unsupported protocol is refused.</summary>
    internal static JavaEntityMetadataKeys For(int protocol) => protocol switch
    {
        47 => Band47,
        107 or 108 or 109 or 110 => Band107,
        210 or 315 or 316 or 335 or 338 or 340 or 393 or 401 or 404 => Band210,
        477 or 480 or 485 or 490 or 498 or 573 or 575 or 578 or 735 or 736 or 751 or 753 or 754 => Band477,
        755 or 756 or 757 or 758 or 759 or 760 or 761 or 762 or 763 or 764 or 765 or 766 or 767 or 768 or 769 or 770 or 771 or 772 or 773 or 774 or 775 or 776 => Band755,
        _ => throw Unsupported(protocol),
    };

    /// <summary>Protocol 47 (1.8.9).</summary>
    private static JavaEntityMetadataKeys Band47 { get; } = new(
        10,
        [
            new(EntityMetadataKeys.SharedFlags, 0),
            new(EntityMetadataKeys.AirSupply, 1),
            new(EntityMetadataKeys.CustomName, 2),
            new(EntityMetadataKeys.CustomNameVisible, 3),
            new(EntityMetadataKeys.Silent, 4),
            new(EntityMetadataKeys.Health, 6),
            new(EntityMetadataKeys.EffectParticles, 7),
            new(EntityMetadataKeys.EffectAmbience, 8),
            new(EntityMetadataKeys.ArrowCount, 9),
        ]);

    /// <summary>Protocols 107 through 110 (1.9 through 1.9.4).</summary>
    private static JavaEntityMetadataKeys Band107 { get; } = new(
        5,
        [
            new(EntityMetadataKeys.SharedFlags, 0),
            new(EntityMetadataKeys.AirSupply, 1),
            new(EntityMetadataKeys.CustomName, 2),
            new(EntityMetadataKeys.CustomNameVisible, 3),
            new(EntityMetadataKeys.Silent, 4),
            new(EntityMetadataKeys.Health, 6),
            new(EntityMetadataKeys.EffectParticles, 7),
            new(EntityMetadataKeys.EffectAmbience, 8),
            new(EntityMetadataKeys.ArrowCount, 9),
        ]);

    /// <summary>Protocols 210 through 404 (1.10.2 through 1.13.2).</summary>
    private static JavaEntityMetadataKeys Band210 { get; } = new(
        6,
        [
            new(EntityMetadataKeys.SharedFlags, 0),
            new(EntityMetadataKeys.AirSupply, 1),
            new(EntityMetadataKeys.CustomName, 2),
            new(EntityMetadataKeys.CustomNameVisible, 3),
            new(EntityMetadataKeys.Silent, 4),
            new(EntityMetadataKeys.NoGravity, 5),
            new(EntityMetadataKeys.Health, 7),
            new(EntityMetadataKeys.EffectParticles, 8),
            new(EntityMetadataKeys.EffectAmbience, 9),
            new(EntityMetadataKeys.ArrowCount, 10),
        ]);

    /// <summary>Protocols 477 through 754 (1.14 through 1.16.5).</summary>
    private static JavaEntityMetadataKeys Band477 { get; } = new(
        7,
        [
            new(EntityMetadataKeys.SharedFlags, 0),
            new(EntityMetadataKeys.AirSupply, 1),
            new(EntityMetadataKeys.CustomName, 2),
            new(EntityMetadataKeys.CustomNameVisible, 3),
            new(EntityMetadataKeys.Silent, 4),
            new(EntityMetadataKeys.NoGravity, 5),
            new(EntityMetadataKeys.Pose, 6),
            new(EntityMetadataKeys.Health, 8),
            new(EntityMetadataKeys.EffectParticles, 9),
            new(EntityMetadataKeys.EffectAmbience, 10),
            new(EntityMetadataKeys.ArrowCount, 11),
        ]);

    /// <summary>Protocols 755 through 776 (1.17 through 26.2).</summary>
    private static JavaEntityMetadataKeys Band755 { get; } = new(
        8,
        [
            new(EntityMetadataKeys.SharedFlags, 0),
            new(EntityMetadataKeys.AirSupply, 1),
            new(EntityMetadataKeys.CustomName, 2),
            new(EntityMetadataKeys.CustomNameVisible, 3),
            new(EntityMetadataKeys.Silent, 4),
            new(EntityMetadataKeys.NoGravity, 5),
            new(EntityMetadataKeys.Pose, 6),
            new(EntityMetadataKeys.TicksFrozen, 7),
            new(EntityMetadataKeys.Health, 9),
            new(EntityMetadataKeys.EffectParticles, 10),
            new(EntityMetadataKeys.EffectAmbience, 11),
            new(EntityMetadataKeys.ArrowCount, 12),
        ]);
}
