// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk;
using Umpk.Protocol.Java;

namespace Umpk.Data.Java.V47;

/// <summary>Generated descriptor for protocol 47 (1.8.9).</summary>
internal static class Descriptor
{
    public static JavaVersion Build()
    {
        var gameVersion = new GameVersion(GameEdition.Java, "1.8.9", 47);
        ProtocolFeatures features = BuildFeatures();
        var builder = new ProtocolDescriptorBuilder(gameVersion, features);

        // Registered packet ids, per phase and flow. PacketRegistrar resolves each to the codec its timeline binds at this protocol, or to a NotImplemented marker.
        PacketRegistrar.Register(builder, ProtocolPhase.Handshake, PacketFlow.Serverbound, 0x00, "minecraft:intention");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x00, "minecraft:login_disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x01, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x02, "minecraft:login_finished");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x03, "minecraft:login_compression");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x00, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x01, "minecraft:key");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x00, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x01, "minecraft:login");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x02, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x03, "minecraft:update_time");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x04, "minecraft:entity_equipment");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x05, "minecraft:spawn_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x06, "minecraft:update_health");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x07, "minecraft:respawn");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x08, "minecraft:player_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x09, "minecraft:held_item_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0A, "minecraft:use_bed");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0B, "minecraft:animate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0C, "minecraft:add_player");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0D, "minecraft:collect_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0E, "minecraft:add_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0F, "minecraft:add_mob");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x10, "minecraft:add_painting");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x11, "minecraft:add_experience_orb");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x12, "minecraft:set_entity_motion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x13, "minecraft:entity_destroy");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x14, "minecraft:entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x15, "minecraft:move_entity_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x16, "minecraft:move_entity_rotation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x17, "minecraft:move_entity_position_rotation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x18, "minecraft:entity_teleport");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x19, "minecraft:rotate_head");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1A, "minecraft:entity_status");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1B, "minecraft:attach_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1C, "minecraft:set_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1D, "minecraft:entity_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1E, "minecraft:remove_entity_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1F, "minecraft:set_experience");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x20, "minecraft:update_attributes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x21, "minecraft:level_chunk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x22, "minecraft:block_change_multi");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x23, "minecraft:block_change");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x24, "minecraft:block_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x25, "minecraft:block_break_animation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x26, "minecraft:map_chunk_bulk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x27, "minecraft:explode");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x28, "minecraft:level_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x29, "minecraft:sound_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2A, "minecraft:level_particles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2B, "minecraft:game_state_change");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2C, "minecraft:spawn_weather_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2D, "minecraft:open_screen");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2E, "minecraft:close_screen");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2F, "minecraft:set_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x30, "minecraft:container_set_content");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x31, "minecraft:craft_progress_bar");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x32, "minecraft:transaction");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x33, "minecraft:update_sign");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x34, "minecraft:map");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x35, "minecraft:block_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x36, "minecraft:open_sign_editor");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x37, "minecraft:statistics");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x38, "minecraft:player_info");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x39, "minecraft:abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3A, "minecraft:tab_complete");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3B, "minecraft:scoreboard_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3C, "minecraft:set_score");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3D, "minecraft:display_scoreboard");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3E, "minecraft:set_player_team");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3F, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x40, "minecraft:disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x41, "minecraft:server_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x42, "minecraft:combat_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x43, "minecraft:camera");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x44, "minecraft:world_border");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x45, "minecraft:title");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x46, "minecraft:set_compression");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x47, "minecraft:player_list_header_footer");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x48, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x49, "minecraft:update_entity_nbt");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x00, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x01, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x02, "minecraft:interact");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x03, "minecraft:move_player");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x04, "minecraft:move_player_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x05, "minecraft:move_player_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x06, "minecraft:move_player_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x07, "minecraft:player_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x08, "minecraft:block_place");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x09, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0A, "minecraft:swing");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0B, "minecraft:player_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0C, "minecraft:steer_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0D, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0E, "minecraft:container_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0F, "minecraft:transaction");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x10, "minecraft:creative_inventory_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x11, "minecraft:container_button_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x12, "minecraft:sign_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x13, "minecraft:abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x14, "minecraft:tab_complete");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x15, "minecraft:client_information");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x16, "minecraft:client_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x17, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x18, "minecraft:spectate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x19, "minecraft:resource_pack_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x00, "minecraft:status_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x01, "minecraft:pong_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x00, "minecraft:status_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x01, "minecraft:ping_request");
        return new JavaVersion(gameVersion, builder.Build(), features);
    }

    // Entity metadata serializer wire order (readable table).
    public static readonly string MetadataTerminator = "0x7f";
    public static readonly (int Id, string Codec)[] MetadataSerializers =
    {
        (0, "Byte"),
        (1, "Short"),
        (2, "Int"),
        (3, "Float"),
        (4, "String"),
        (5, "ItemStack"),
        (6, "BlockPos"),
        (7, "Rotations"),
    };

    private static ProtocolFeatures BuildFeatures() => new ProtocolFeatures
    {
        BlockPosLayout = "legacy",
        ChatSigning = "none",
        ConfigurationPhase = false,
        CrawlPose = false,
        Elytra = false,
        FluidMovement = "swimmingUpdate",
        NbtWireFormat = "javaNamedRoot",
        SwimPose = false,
        WaterClimbBump = false,
        WaterTravel = "legacy",
    };

    // Table references (shared across versions by content; Vn names the earliest owning protocol).
    public static ReadOnlySpan<byte> ItemNames => SharedTables.ItemsV47;
    public static ReadOnlySpan<byte> LegacyItemDefs => SharedTables.LegacyItemsV47;
    public static ReadOnlySpan<byte> BlockNames => SharedTables.BlocksV47;
    public static ReadOnlySpan<byte> BlockDefs => SharedTables.BlockDefinitionsV47;
    public static ReadOnlySpan<byte> EntityNames => SharedTables.EntitiesV47;
    public static ReadOnlySpan<byte> SoundNames => SharedTables.SoundsV47;
    public static ReadOnlySpan<byte> LegacyObjectEntityNames => SharedTables.LegacyObjectEntitiesV47;
    public static ReadOnlySpan<byte> MenuDefs => SharedTables.MenusV47;
    public static ReadOnlySpan<byte> CollisionShapes => SharedTables.CollisionShapesV47;
    public static ReadOnlySpan<byte> BlockShapeRefs => SharedTables.BlockShapeReferencesV47;
    public static ReadOnlySpan<byte> BlockAttrs => SharedTables.BlockAttributesV47;
    public static ReadOnlySpan<byte> BlockPush => SharedTables.BlockPushV47;
    public static ReadOnlySpan<byte> EnchantmentDefs => SharedTables.EnchantmentsV47;
    public static ReadOnlySpan<byte> MobEffectDefs => SharedTables.MobEffectsV47;
    public static ReadOnlySpan<byte> AttributeDefs => SharedTables.AttributesV47;
}
