// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk;
using Umpk.Protocol.Java;

namespace Umpk.Data.Java.V763;

/// <summary>Generated descriptor for protocol 763 (1.20.1).</summary>
internal static class Descriptor
{
    public static JavaVersion Build()
    {
        var gameVersion = new GameVersion(GameEdition.Java, "1.20.1", 763);
        ProtocolFeatures features = BuildFeatures();
        var builder = new ProtocolDescriptorBuilder(gameVersion, features);

        // Registered packet ids, per phase and flow. PacketRegistrar resolves each to the codec its timeline binds at this protocol, or to a NotImplemented marker.
        PacketRegistrar.Register(builder, ProtocolPhase.Handshake, PacketFlow.Serverbound, 0x00, "minecraft:intention");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x00, "minecraft:login_disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x01, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x02, "minecraft:login_finished");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x03, "minecraft:login_compression");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x04, "minecraft:custom_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x00, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x01, "minecraft:key");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x02, "minecraft:custom_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x03, "minecraft:bundle_delimiter");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x00, "minecraft:bundle_delimiter");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x01, "minecraft:add_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x02, "minecraft:add_experience_orb");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x03, "minecraft:add_player");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x04, "minecraft:animate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x05, "minecraft:award_stats");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x06, "minecraft:block_changed_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x07, "minecraft:block_destruction");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x08, "minecraft:block_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x09, "minecraft:block_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0A, "minecraft:block_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0B, "minecraft:boss_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0C, "minecraft:change_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0D, "minecraft:chunks_biomes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0E, "minecraft:clear_titles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0F, "minecraft:command_suggestions");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x10, "minecraft:commands");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x11, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x12, "minecraft:container_set_content");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x13, "minecraft:container_set_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x14, "minecraft:container_set_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x15, "minecraft:cooldown");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x16, "minecraft:custom_chat_completions");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x17, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x18, "minecraft:damage_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x19, "minecraft:delete_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1A, "minecraft:disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1B, "minecraft:disguised_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1C, "minecraft:entity_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1D, "minecraft:explode");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1E, "minecraft:forget_level_chunk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1F, "minecraft:game_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x20, "minecraft:horse_screen_open");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x21, "minecraft:hurt_animation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x22, "minecraft:initialize_border");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x23, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x24, "minecraft:level_chunk_with_light");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x25, "minecraft:level_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x26, "minecraft:level_particles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x27, "minecraft:light_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x28, "minecraft:login");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x29, "minecraft:map_item_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2A, "minecraft:merchant_offers");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2B, "minecraft:move_entity_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2C, "minecraft:move_entity_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2D, "minecraft:move_entity_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2E, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2F, "minecraft:open_book");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x30, "minecraft:open_screen");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x31, "minecraft:open_sign_editor");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x32, "minecraft:ping");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x33, "minecraft:place_ghost_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x34, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x35, "minecraft:player_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x36, "minecraft:player_combat_end");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x37, "minecraft:player_combat_enter");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x38, "minecraft:player_combat_kill");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x39, "minecraft:player_info_remove");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3A, "minecraft:player_info_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3B, "minecraft:player_look_at");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3C, "minecraft:player_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3D, "minecraft:recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3E, "minecraft:remove_entities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3F, "minecraft:remove_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x40, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x41, "minecraft:respawn");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x42, "minecraft:rotate_head");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x43, "minecraft:section_blocks_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x44, "minecraft:select_advancements_tab");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x45, "minecraft:server_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x46, "minecraft:set_action_bar_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x47, "minecraft:set_border_center");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x48, "minecraft:set_border_lerp_size");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x49, "minecraft:set_border_size");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4A, "minecraft:set_border_warning_delay");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4B, "minecraft:set_border_warning_distance");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4C, "minecraft:set_camera");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4D, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4E, "minecraft:set_chunk_cache_center");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4F, "minecraft:set_chunk_cache_radius");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x50, "minecraft:set_default_spawn_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x51, "minecraft:set_display_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x52, "minecraft:set_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x53, "minecraft:set_entity_link");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x54, "minecraft:set_entity_motion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x55, "minecraft:set_equipment");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x56, "minecraft:set_experience");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x57, "minecraft:set_health");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x58, "minecraft:set_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x59, "minecraft:set_passengers");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5A, "minecraft:set_player_team");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5B, "minecraft:set_score");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5C, "minecraft:set_simulation_distance");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5D, "minecraft:set_subtitle_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5E, "minecraft:set_time");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5F, "minecraft:set_title_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x60, "minecraft:set_titles_animation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x61, "minecraft:sound_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x62, "minecraft:sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x63, "minecraft:stop_sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x64, "minecraft:system_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x65, "minecraft:tab_list");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x66, "minecraft:tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x67, "minecraft:take_item_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x68, "minecraft:teleport_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x69, "minecraft:update_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6A, "minecraft:update_attributes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6B, "minecraft:update_enabled_features");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6C, "minecraft:update_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6D, "minecraft:update_recipes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6E, "minecraft:update_tags");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x00, "minecraft:accept_teleportation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x01, "minecraft:block_entity_tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x02, "minecraft:change_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x03, "minecraft:chat_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x04, "minecraft:chat_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x05, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x06, "minecraft:chat_session_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x07, "minecraft:client_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x08, "minecraft:client_information");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x09, "minecraft:command_suggestion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0A, "minecraft:container_button_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0B, "minecraft:container_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0C, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0D, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0E, "minecraft:edit_book");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0F, "minecraft:entity_tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x10, "minecraft:interact");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x11, "minecraft:jigsaw_generate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x12, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x13, "minecraft:lock_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x14, "minecraft:move_player_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x15, "minecraft:move_player_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x16, "minecraft:move_player_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x17, "minecraft:move_player_status_only");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x18, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x19, "minecraft:paddle_boat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1A, "minecraft:pick_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1B, "minecraft:place_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1C, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1D, "minecraft:player_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1E, "minecraft:player_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1F, "minecraft:player_input");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x20, "minecraft:pong");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x21, "minecraft:recipe_book_change_settings");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x22, "minecraft:recipe_book_seen_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x23, "minecraft:rename_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x24, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x25, "minecraft:seen_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x26, "minecraft:select_trade");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x27, "minecraft:set_beacon");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x28, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x29, "minecraft:set_command_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2A, "minecraft:set_command_minecart");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2B, "minecraft:set_creative_mode_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2C, "minecraft:set_jigsaw_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2D, "minecraft:set_structure_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2E, "minecraft:sign_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2F, "minecraft:swing");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x30, "minecraft:teleport_to_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x31, "minecraft:use_item_on");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x32, "minecraft:use_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x00, "minecraft:status_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x01, "minecraft:pong_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x00, "minecraft:status_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x01, "minecraft:ping_request");
        return new JavaVersion(gameVersion, builder.Build(), features);
    }

    // Entity metadata serializer wire order (readable table).
    public static readonly string MetadataTerminator = "0xff";
    public static readonly (int Id, string Codec)[] MetadataSerializers =
    {
        (0, "Byte"),
        (1, "VarInt"),
        (2, "VarLong"),
        (3, "Float"),
        (4, "String"),
        (5, "Component"),
        (6, "OptionalComponent"),
        (7, "ItemStack"),
        (8, "Boolean"),
        (9, "Rotations"),
        (10, "BlockPos"),
        (11, "OptionalBlockPos"),
        (12, "Direction"),
        (13, "OptionalUuid"),
        (14, "BlockState"),
        (15, "OptionalBlockState"),
        (16, "CompoundTag"),
        (17, "Particle"),
        (18, "VillagerData"),
        (19, "OptionalUnsignedInt"),
        (20, "Pose"),
        (21, "CatVariant"),
        (22, "FrogVariant"),
        (23, "OptionalGlobalPos"),
        (24, "PaintingVariant"),
        (25, "SnifferState"),
        (26, "Vector3"),
        (27, "Quaternion"),
    };

    private static ProtocolFeatures BuildFeatures() => new ProtocolFeatures
    {
        ArgumentTypeEra = "v1_20",
        BlockPosLayout = "modern",
        ChatSigning = "v3",
        ComponentInteractionEra = "legacy",
        ConfigurationPhase = false,
        CrawlPose = true,
        Elytra = true,
        FluidMovement = "swimmingUpdate",
        NbtWireFormat = "javaNamedRoot",
        SwimPose = true,
        WaterClimbBump = true,
        WaterTravel = "sprintAware",
    };

    // Table references (shared across versions by content; Vn names the earliest owning protocol).
    public static ReadOnlySpan<byte> ItemNames => SharedTables.ItemsV763;
    public static ReadOnlySpan<byte> BlockNames => SharedTables.BlocksV763;
    public static ReadOnlySpan<byte> BlockDefs => SharedTables.BlockDefinitionsV763;
    public static ReadOnlySpan<byte> EntityNames => SharedTables.EntitiesV762;
    public static ReadOnlySpan<byte> SoundNames => SharedTables.SoundsV763;
    public static ReadOnlySpan<byte> LegacyObjectEntityNames => SharedTables.LegacyObjectEntitiesV477;
    public static ReadOnlySpan<byte> MenuDefs => SharedTables.MenusV735;
    public static ReadOnlySpan<byte> CollisionShapes => SharedTables.CollisionShapesV763;
    public static ReadOnlySpan<byte> BlockShapeRefs => SharedTables.BlockShapeReferencesV763;
    public static ReadOnlySpan<byte> BlockAttrs => SharedTables.BlockAttributesV763;
    public static ReadOnlySpan<byte> BlockPush => SharedTables.BlockPushV763;
    public static ReadOnlySpan<byte> EnchantmentDefs => SharedTables.EnchantmentsV759;
    public static ReadOnlySpan<byte> MobEffectDefs => SharedTables.MobEffectsV759;
    public static ReadOnlySpan<byte> AttributeDefs => SharedTables.AttributesV735;
}
