<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Umpk.Realms/Umpk.Realms.csproj" />
    <ProjectReference Include="../../src/Umpk.Auth/Umpk.Auth.csproj" />
  </ItemGroup>
</Project>
