// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk;
using Umpk.Protocol.Java;

namespace Umpk.Data.Java.V776;

/// <summary>Generated descriptor for protocol 776 (26.2).</summary>
internal static class Descriptor
{
    public static JavaVersion Build()
    {
        var gameVersion = new GameVersion(GameEdition.Java, "26.2", 776);
        ProtocolFeatures features = BuildFeatures();
        var builder = new ProtocolDescriptorBuilder(gameVersion, features);

        // Registered packet ids, per phase and flow. PacketRegistrar resolves each to the codec its timeline binds at this protocol, or to a NotImplemented marker.
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x00, "minecraft:cookie_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x01, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x02, "minecraft:disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x03, "minecraft:finish_configuration");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x04, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x05, "minecraft:ping");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x06, "minecraft:reset_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x07, "minecraft:registry_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x08, "minecraft:resource_pack_pop");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x09, "minecraft:resource_pack_push");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0A, "minecraft:store_cookie");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0B, "minecraft:transfer");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0C, "minecraft:update_enabled_features");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0D, "minecraft:update_tags");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0E, "minecraft:select_known_packs");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x0F, "minecraft:custom_report_details");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x10, "minecraft:server_links");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x11, "minecraft:clear_dialog");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x12, "minecraft:show_dialog");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Clientbound, 0x13, "minecraft:code_of_conduct");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x00, "minecraft:client_information");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x01, "minecraft:cookie_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x02, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x03, "minecraft:finish_configuration");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x04, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x05, "minecraft:pong");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x06, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x07, "minecraft:select_known_packs");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x08, "minecraft:custom_click_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Configuration, PacketFlow.Serverbound, 0x09, "minecraft:accept_code_of_conduct");
        PacketRegistrar.Register(builder, ProtocolPhase.Handshake, PacketFlow.Serverbound, 0x00, "minecraft:intention");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x00, "minecraft:login_disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x01, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x02, "minecraft:login_finished");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x03, "minecraft:login_compression");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x04, "minecraft:custom_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x05, "minecraft:cookie_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x00, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x01, "minecraft:key");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x02, "minecraft:custom_query_answer");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x03, "minecraft:login_acknowledged");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x04, "minecraft:cookie_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x00, "minecraft:bundle_delimiter");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x01, "minecraft:add_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x02, "minecraft:animate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x03, "minecraft:award_stats");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x04, "minecraft:block_changed_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x05, "minecraft:block_destruction");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x06, "minecraft:block_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x07, "minecraft:block_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x08, "minecraft:block_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x09, "minecraft:boss_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0A, "minecraft:change_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0B, "minecraft:chunk_batch_finished");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0C, "minecraft:chunk_batch_start");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0D, "minecraft:chunks_biomes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0E, "minecraft:clear_titles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0F, "minecraft:command_suggestions");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x10, "minecraft:commands");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x11, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x12, "minecraft:container_set_content");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x13, "minecraft:container_set_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x14, "minecraft:container_set_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x15, "minecraft:cookie_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x16, "minecraft:cooldown");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x17, "minecraft:custom_chat_completions");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x18, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x19, "minecraft:damage_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1A, "minecraft:debug/block_value");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1B, "minecraft:debug/chunk_value");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1C, "minecraft:debug/entity_value");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1D, "minecraft:debug/event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1E, "minecraft:debug_sample");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1F, "minecraft:delete_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x20, "minecraft:disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x21, "minecraft:disguised_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x22, "minecraft:entity_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x23, "minecraft:entity_position_sync");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x24, "minecraft:explode");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x25, "minecraft:forget_level_chunk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x26, "minecraft:game_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x27, "minecraft:game_rule_values");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x28, "minecraft:game_test_highlight_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x29, "minecraft:mount_screen_open");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2A, "minecraft:hurt_animation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2B, "minecraft:initialize_border");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2C, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2D, "minecraft:level_chunk_with_light");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2E, "minecraft:level_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2F, "minecraft:level_particles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x30, "minecraft:light_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x31, "minecraft:login");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x32, "minecraft:low_disk_space_warning");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x33, "minecraft:map_item_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x34, "minecraft:merchant_offers");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x35, "minecraft:move_entity_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x36, "minecraft:move_entity_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x37, "minecraft:move_minecart_along_track");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x38, "minecraft:move_entity_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x39, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3A, "minecraft:open_book");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3B, "minecraft:open_screen");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3C, "minecraft:open_sign_editor");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3D, "minecraft:ping");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3E, "minecraft:pong_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3F, "minecraft:place_ghost_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x40, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x41, "minecraft:player_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x42, "minecraft:player_combat_end");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x43, "minecraft:player_combat_enter");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x44, "minecraft:player_combat_kill");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x45, "minecraft:player_info_remove");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x46, "minecraft:player_info_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x47, "minecraft:player_look_at");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x48, "minecraft:player_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x49, "minecraft:player_rotation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4A, "minecraft:recipe_book_add");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4B, "minecraft:recipe_book_remove");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4C, "minecraft:recipe_book_settings");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4D, "minecraft:remove_entities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4E, "minecraft:remove_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4F, "minecraft:reset_score");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x50, "minecraft:resource_pack_pop");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x51, "minecraft:resource_pack_push");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x52, "minecraft:respawn");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x53, "minecraft:rotate_head");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x54, "minecraft:section_blocks_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x55, "minecraft:select_advancements_tab");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x56, "minecraft:server_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x57, "minecraft:set_action_bar_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x58, "minecraft:set_border_center");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x59, "minecraft:set_border_lerp_size");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5A, "minecraft:set_border_size");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5B, "minecraft:set_border_warning_delay");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5C, "minecraft:set_border_warning_distance");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5D, "minecraft:set_camera");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5E, "minecraft:set_chunk_cache_center");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x5F, "minecraft:set_chunk_cache_radius");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x60, "minecraft:set_cursor_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x61, "minecraft:set_default_spawn_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x62, "minecraft:set_display_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x63, "minecraft:set_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x64, "minecraft:set_entity_link");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x65, "minecraft:set_entity_motion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x66, "minecraft:set_equipment");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x67, "minecraft:set_experience");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x68, "minecraft:set_health");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x69, "minecraft:set_held_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6A, "minecraft:set_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6B, "minecraft:set_passengers");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6C, "minecraft:set_player_inventory");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6D, "minecraft:set_player_team");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6E, "minecraft:set_score");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x6F, "minecraft:set_simulation_distance");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x70, "minecraft:set_subtitle_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x71, "minecraft:set_time");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x72, "minecraft:set_title_text");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x73, "minecraft:set_titles_animation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x74, "minecraft:sound_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x75, "minecraft:sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x76, "minecraft:start_configuration");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x77, "minecraft:stop_sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x78, "minecraft:store_cookie");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x79, "minecraft:system_chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7A, "minecraft:tab_list");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7B, "minecraft:tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7C, "minecraft:take_item_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7D, "minecraft:teleport_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7E, "minecraft:test_instance_block_status");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x7F, "minecraft:ticking_state");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x80, "minecraft:ticking_step");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x81, "minecraft:transfer");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x82, "minecraft:update_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x83, "minecraft:update_attributes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x84, "minecraft:update_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x85, "minecraft:update_recipes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x86, "minecraft:update_tags");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x87, "minecraft:projectile_power");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x88, "minecraft:custom_report_details");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x89, "minecraft:server_links");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x8A, "minecraft:waypoint");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x8B, "minecraft:clear_dialog");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x8C, "minecraft:show_dialog");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x00, "minecraft:accept_teleportation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x01, "minecraft:attack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x02, "minecraft:block_entity_tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x03, "minecraft:bundle_item_selected");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x04, "minecraft:change_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x05, "minecraft:change_game_mode");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x06, "minecraft:chat_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x07, "minecraft:chat_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x08, "minecraft:chat_command_signed");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x09, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0A, "minecraft:chat_session_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0B, "minecraft:chunk_batch_received");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0C, "minecraft:client_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0D, "minecraft:client_tick_end");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0E, "minecraft:client_information");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0F, "minecraft:command_suggestion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x10, "minecraft:configuration_acknowledged");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x11, "minecraft:container_button_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x12, "minecraft:container_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x13, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x14, "minecraft:container_slot_state_changed");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x15, "minecraft:cookie_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x16, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x17, "minecraft:debug_subscription_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x18, "minecraft:edit_book");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x19, "minecraft:entity_tag_query");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1A, "minecraft:interact");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1B, "minecraft:jigsaw_generate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1C, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1D, "minecraft:lock_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1E, "minecraft:move_player_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1F, "minecraft:move_player_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x20, "minecraft:move_player_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x21, "minecraft:move_player_status_only");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x22, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x23, "minecraft:paddle_boat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x24, "minecraft:pick_item_from_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x25, "minecraft:pick_item_from_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x26, "minecraft:ping_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x27, "minecraft:place_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x28, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x29, "minecraft:player_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2A, "minecraft:player_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2B, "minecraft:player_input");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2C, "minecraft:player_loaded");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2D, "minecraft:pong");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2E, "minecraft:recipe_book_change_settings");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x2F, "minecraft:recipe_book_seen_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x30, "minecraft:rename_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x31, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x32, "minecraft:seen_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x33, "minecraft:select_trade");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x34, "minecraft:set_beacon");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x35, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x36, "minecraft:set_command_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x37, "minecraft:set_command_minecart");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x38, "minecraft:set_creative_mode_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x39, "minecraft:set_game_rule");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3A, "minecraft:set_jigsaw_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3B, "minecraft:set_structure_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3C, "minecraft:set_test_block");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3D, "minecraft:sign_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3E, "minecraft:spectator_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x3F, "minecraft:swing");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x40, "minecraft:teleport_to_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x41, "minecraft:test_instance_block_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x42, "minecraft:use_item_on");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x43, "minecraft:use_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x44, "minecraft:custom_click_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x00, "minecraft:status_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x01, "minecraft:pong_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x00, "minecraft:status_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x01, "minecraft:ping_request");
        return new JavaVersion(gameVersion, builder.Build(), features);
    }

    // Entity metadata serializer wire order (readable table).
    public static readonly string MetadataTerminator = "0xff";
    public static readonly (int Id, string Codec)[] MetadataSerializers =
    {
        (0, "Byte"),
        (1, "VarInt"),
        (2, "VarLong"),
        (3, "Float"),
        (4, "String"),
        (5, "Component"),
        (6, "OptionalComponent"),
        (7, "ItemStack"),
        (8, "Boolean"),
        (9, "Rotations"),
        (10, "BlockPos"),
        (11, "OptionalBlockPos"),
        (12, "Direction"),
        (13, "OptionalLivingEntityReference"),
        (14, "BlockState"),
        (15, "OptionalBlockState"),
        (16, "Particle"),
        (17, "Particles"),
        (18, "VillagerData"),
        (19, "OptionalUnsignedInt"),
        (20, "Pose"),
        (21, "CatVariant"),
        (22, "CatSoundVariant"),
        (23, "CowVariant"),
        (24, "CowSoundVariant"),
        (25, "WolfVariant"),
        (26, "WolfSoundVariant"),
        (27, "FrogVariant"),
        (28, "PigVariant"),
        (29, "PigSoundVariant"),
        (30, "ChickenVariant"),
        (31, "ChickenSoundVariant"),
        (32, "ZombieNautilusVariant"),
        (33, "OptionalGlobalPos"),
        (34, "PaintingVariant"),
        (35, "SnifferState"),
        (36, "ArmadilloState"),
        (37, "CopperGolemState"),
        (38, "WeatheringCopperState"),
        (39, "Vector3"),
        (40, "Quaternion"),
        (41, "ResolvableProfile"),
        (42, "HumanoidArm"),
    };

    private static ProtocolFeatures BuildFeatures() => new ProtocolFeatures
    {
        ArgumentTypeEra = "v26_2",
        BlockPosLayout = "modern",
        ChatSigning = "v3",
        ConfigurationPhase = true,
        CrawlPose = true,
        Elytra = true,
        FluidMovement = "swimmingUpdate",
        NbtWireFormat = "javaRootTagOrString",
        SwimPose = true,
        WaterClimbBump = true,
        WaterTravel = "sprintAware",
    };

    // Table references (shared across versions by content; Vn names the earliest owning protocol).
    public static ReadOnlySpan<byte> ItemNames => SharedTables.ItemsV776;
    public static ReadOnlySpan<byte> BlockNames => SharedTables.BlocksV776;
    public static ReadOnlySpan<byte> BlockDefs => SharedTables.BlockDefinitionsV776;
    public static ReadOnlySpan<byte> EntityNames => SharedTables.EntitiesV776;
    public static ReadOnlySpan<byte> SoundNames => SharedTables.SoundsV776;
    public static ReadOnlySpan<byte> LegacyObjectEntityNames => SharedTables.LegacyObjectEntitiesV477;
    public static ReadOnlySpan<byte> MenuDefs => SharedTables.MenusV765;
    public static ReadOnlySpan<byte> CollisionShapes => SharedTables.CollisionShapesV776;
    public static ReadOnlySpan<byte> BlockShapeRefs => SharedTables.BlockShapeReferencesV776;
    public static ReadOnlySpan<byte> BlockAttrs => SharedTables.BlockAttributesV776;
    public static ReadOnlySpan<byte> BlockPush => SharedTables.BlockPushV776;
    public static ReadOnlySpan<byte> EnchantmentDefs => SharedTables.EnchantmentsV47;
    public static ReadOnlySpan<byte> MobEffectDefs => SharedTables.MobEffectsV774;
    public static ReadOnlySpan<byte> AttributeDefs => SharedTables.AttributesV776;
}
