// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk;
using Umpk.Protocol.Java;

namespace Umpk.Data.Java.V340;

/// <summary>Generated descriptor for protocol 340 (1.12.2).</summary>
internal static class Descriptor
{
    public static JavaVersion Build()
    {
        var gameVersion = new GameVersion(GameEdition.Java, "1.12.2", 340);
        ProtocolFeatures features = BuildFeatures();
        var builder = new ProtocolDescriptorBuilder(gameVersion, features);

        // Registered packet ids, per phase and flow. PacketRegistrar resolves each to the codec its timeline binds at this protocol, or to a NotImplemented marker.
        PacketRegistrar.Register(builder, ProtocolPhase.Handshake, PacketFlow.Serverbound, 0x00, "minecraft:intention");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x00, "minecraft:login_disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x01, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x02, "minecraft:login_finished");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Clientbound, 0x03, "minecraft:login_compression");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x00, "minecraft:hello");
        PacketRegistrar.Register(builder, ProtocolPhase.Login, PacketFlow.Serverbound, 0x01, "minecraft:key");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x00, "minecraft:add_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x01, "minecraft:add_experience_orb");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x02, "minecraft:add_global_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x03, "minecraft:add_mob");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x04, "minecraft:add_painting");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x05, "minecraft:add_player");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x06, "minecraft:animate");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x07, "minecraft:award_stats");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x08, "minecraft:block_destruction");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x09, "minecraft:block_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0A, "minecraft:block_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0B, "minecraft:block_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0C, "minecraft:boss_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0D, "minecraft:change_difficulty");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0E, "minecraft:command_suggestions");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x0F, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x10, "minecraft:chunk_blocks_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x11, "minecraft:container_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x12, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x13, "minecraft:open_screen");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x14, "minecraft:container_set_content");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x15, "minecraft:container_set_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x16, "minecraft:container_set_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x17, "minecraft:cooldown");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x18, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x19, "minecraft:custom_sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1A, "minecraft:disconnect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1B, "minecraft:entity_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1C, "minecraft:explode");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1D, "minecraft:forget_level_chunk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1E, "minecraft:game_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x1F, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x20, "minecraft:level_chunk");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x21, "minecraft:level_event");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x22, "minecraft:level_particles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x23, "minecraft:login");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x24, "minecraft:map_item_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x25, "minecraft:move_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x26, "minecraft:move_entity_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x27, "minecraft:move_entity_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x28, "minecraft:move_entity_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x29, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2A, "minecraft:open_sign_editor");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2B, "minecraft:place_ghost_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2C, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2D, "minecraft:player_combat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2E, "minecraft:player_info");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x2F, "minecraft:player_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x30, "minecraft:use_bed");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x31, "minecraft:recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x32, "minecraft:remove_entities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x33, "minecraft:remove_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x34, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x35, "minecraft:respawn");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x36, "minecraft:rotate_head");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x37, "minecraft:select_advancements_tab");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x38, "minecraft:set_border");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x39, "minecraft:set_camera");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3A, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3B, "minecraft:set_display_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3C, "minecraft:set_entity_data");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3D, "minecraft:set_entity_link");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3E, "minecraft:set_entity_motion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x3F, "minecraft:set_equipped_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x40, "minecraft:set_experience");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x41, "minecraft:set_health");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x42, "minecraft:set_objective");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x43, "minecraft:set_passengers");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x44, "minecraft:set_player_team");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x45, "minecraft:set_score");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x46, "minecraft:set_spawn_position");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x47, "minecraft:set_time");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x48, "minecraft:set_titles");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x49, "minecraft:sound");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4A, "minecraft:tab_list");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4B, "minecraft:take_item_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4C, "minecraft:teleport_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4D, "minecraft:update_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4E, "minecraft:update_attributes");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x4F, "minecraft:update_mob_effect");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x00, "minecraft:accept_teleportation");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x01, "minecraft:command_suggestion");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x02, "minecraft:chat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x03, "minecraft:client_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x04, "minecraft:client_information");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x05, "minecraft:container_ack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x06, "minecraft:container_button_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x07, "minecraft:container_click");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x08, "minecraft:container_close");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x09, "minecraft:custom_payload");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0A, "minecraft:interact");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0B, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0C, "minecraft:move_player");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0D, "minecraft:move_player_pos");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0E, "minecraft:move_player_pos_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x0F, "minecraft:move_player_rot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x10, "minecraft:move_vehicle");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x11, "minecraft:paddle_boat");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x12, "minecraft:place_recipe");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x13, "minecraft:player_abilities");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x14, "minecraft:player_action");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x15, "minecraft:player_command");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x16, "minecraft:player_input");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x17, "minecraft:recipe_book_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x18, "minecraft:resource_pack");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x19, "minecraft:seen_advancements");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1A, "minecraft:set_carried_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1B, "minecraft:set_creative_mode_slot");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1C, "minecraft:sign_update");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1D, "minecraft:swing");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1E, "minecraft:teleport_to_entity");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x1F, "minecraft:use_item_on");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Serverbound, 0x20, "minecraft:use_item");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x00, "minecraft:status_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Clientbound, 0x01, "minecraft:pong_response");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x00, "minecraft:status_request");
        PacketRegistrar.Register(builder, ProtocolPhase.Status, PacketFlow.Serverbound, 0x01, "minecraft:ping_request");
        return new JavaVersion(gameVersion, builder.Build(), features);
    }

    // Entity metadata serializer wire order (readable table).
    public static readonly string MetadataTerminator = "0xff";
    public static readonly (int Id, string Codec)[] MetadataSerializers =
    {
        (0, "Byte"),
        (1, "VarInt"),
        (2, "Float"),
        (3, "String"),
        (4, "Component"),
        (5, "ItemStack"),
        (6, "Boolean"),
        (7, "Rotations"),
        (8, "BlockPos"),
        (9, "OptionalBlockPos"),
        (10, "Direction"),
        (11, "OptionalUuid"),
        (12, "BlockState"),
        (13, "CompoundTag"),
    };

    private static ProtocolFeatures BuildFeatures() => new ProtocolFeatures
    {
        ArgumentTypeEra = "none",
        BlockPosLayout = "legacy",
        ChatSigning = "none",
        ComponentInteractionEra = "legacy",
        ConfigurationPhase = false,
        CrawlPose = false,
        Elytra = true,
        FluidMovement = "swimmingUpdate",
        NbtWireFormat = "javaNamedRoot",
        SwimPose = false,
        WaterClimbBump = false,
        WaterTravel = "legacy",
    };

    // Table references (shared across versions by content; Vn names the earliest owning protocol).
    public static ReadOnlySpan<byte> ItemNames => SharedTables.ItemsV335;
    public static ReadOnlySpan<byte> LegacyItemDefs => SharedTables.LegacyItemsV335;
    public static ReadOnlySpan<byte> BlockNames => SharedTables.BlocksV335;
    public static ReadOnlySpan<byte> BlockDefs => SharedTables.BlockDefinitionsV335;
    public static ReadOnlySpan<byte> EntityNames => SharedTables.EntitiesV335;
    public static ReadOnlySpan<byte> SoundNames => SharedTables.SoundsV47;
    public static ReadOnlySpan<byte> LegacyObjectEntityNames => SharedTables.LegacyObjectEntitiesV315;
    public static ReadOnlySpan<byte> MenuDefs => SharedTables.MenusV315;
    public static ReadOnlySpan<byte> CollisionShapes => SharedTables.CollisionShapesV107;
    public static ReadOnlySpan<byte> BlockShapeRefs => SharedTables.BlockShapeReferencesV335;
    public static ReadOnlySpan<byte> BlockAttrs => SharedTables.BlockAttributesV335;
    public static ReadOnlySpan<byte> BlockPush => SharedTables.BlockPushV47;
    public static ReadOnlySpan<byte> EnchantmentDefs => SharedTables.EnchantmentsV47;
    public static ReadOnlySpan<byte> MobEffectDefs => SharedTables.MobEffectsV107;
    public static ReadOnlySpan<byte> AttributeDefs => SharedTables.AttributesV47;
}
