// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk;
using Umpk.Protocol.Java;

namespace Umpk.Data.Java.V47;

/// <summary>Generated descriptor for protocol 47 (1.8).</summary>
internal static class Descriptor
{
    public static JavaVersion Build()
    {
        var gameVersion = new GameVersion(GameEdition.Java, "1.8", 47);
        ProtocolFeatures features = BuildFeatures();
        var builder = new ProtocolDescriptorBuilder(gameVersion, features);

        // Registered packet ids, per phase and flow. PacketRegistrar resolves each to the codec its timeline binds at this protocol, or to a NotImplemented marker.
        PacketRegistrar.Register(builder, ProtocolPhase.Handshake, PacketFlow.Serverbound, 0x00, "minecraft:intention");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x00, "minecraft:keep_alive");
        PacketRegistrar.Register(builder, ProtocolPhase.Play, PacketFlow.Clientbound, 0x01, "minecraft:login");
        return new JavaVersion(gameVersion, builder.Build(), features);
    }

    // Entity metadata serializer wire order (readable table).
    public static readonly string MetadataTerminator = "0x7f";
    public static readonly (int Id, string Codec)[] MetadataSerializers =
    {
        (0, "Byte"),
    };

    private static ProtocolFeatures BuildFeatures() => new ProtocolFeatures
    {
        ChatSigning = "v3",
        ConfigurationPhase = true,
    };

    // Table references (shared across versions by content; Vn names the earliest owning protocol).
    public static ReadOnlySpan<byte> ItemNames => SharedTables.ItemsV47;
    public static ReadOnlySpan<byte> LegacyItemDefs => SharedTables.LegacyItemsV47;
    public static ReadOnlySpan<byte> BlockNames => SharedTables.BlocksV47;
    public static ReadOnlySpan<byte> BlockDefs => SharedTables.BlockDefinitionsV47;
    public static ReadOnlySpan<byte> EntityNames => SharedTables.EntitiesV47;
    public static ReadOnlySpan<byte> SoundNames => SharedTables.SoundsV47;
    public static ReadOnlySpan<byte> LegacyObjectEntityNames => SharedTables.LegacyObjectEntitiesV47;
    public static ReadOnlySpan<byte> MenuDefs => SharedTables.MenusV47;
    public static ReadOnlySpan<byte> CollisionShapes => SharedTables.CollisionShapesV47;
    public static ReadOnlySpan<byte> BlockShapeRefs => SharedTables.BlockShapeReferencesV47;
    public static ReadOnlySpan<byte> BlockAttrs => SharedTables.BlockAttributesV47;
    public static ReadOnlySpan<byte> BlockPush => SharedTables.BlockPushV47;
    public static ReadOnlySpan<byte> EnchantmentDefs => SharedTables.EnchantmentsV47;
    public static ReadOnlySpan<byte> MobEffectDefs => SharedTables.MobEffectsV47;
    public static ReadOnlySpan<byte> AttributeDefs => SharedTables.AttributesV47;
}
