// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out src/Umpk.Data.Java
// </auto-generated>
#nullable enable

using Umpk.Protocol.Java;

namespace Umpk.Data.Java;

/// <summary>Generated version catalog. Implements the IVersionCatalog seam.</summary>
/// <remarks>Trimming-load-bearing shape (normative): no static constructor and no static field initializers. Every V* property lazily constructs through its own backing field so the trimmer can drop unreferenced versions. All and TryGetBy* obey the same rule: lazy bodies, no static initializers, so touching one V* property never roots the whole catalog.</remarks>
public static class JavaVersions
{
    /// <summary>1.8 (protocol 47).</summary>
    public static JavaVersion V1_8 => s_v47 ??= global::Umpk.Data.Java.V47.Descriptor.Build();
    private static JavaVersion? s_v47;

    /// <summary>1.21.5 (protocol 770).</summary>
    public static JavaVersion V1_21_5 => s_v770 ??= global::Umpk.Data.Java.V770.Descriptor.Build();
    private static JavaVersion? s_v770;

    /// <summary>All supported versions. References every version and therefore roots the full data set.</summary>
    public static IReadOnlyList<JavaVersion> All => s_all ??= BuildAll();
    private static IReadOnlyList<JavaVersion>? s_all;

    private static IReadOnlyList<JavaVersion> BuildAll() =>
        new JavaVersion[] { V1_8, V1_21_5 };

    /// <summary>Look up a version by protocol number. Walks All lazily.</summary>
    public static bool TryGetByProtocol(int protocol, out JavaVersion version)
    {
        foreach (JavaVersion candidate in All)
        {
            if (candidate.Version.Protocol == protocol)
            {
                version = candidate;
                return true;
            }
        }
        version = default!;
        return false;
    }

    /// <summary>Look up a version by name ("1.21.5"). Resolves N:1 aliases ("1.20.3" and "1.20.4" both map to protocol 765) via the generated name table, which the single-name <c>JavaVersion.HasName</c> cannot express.</summary>
    public static bool TryGetByName(string name, out JavaVersion version)
    {
        int protocol = name switch
        {
            "1.8" => 47,
            "1.21.5" => 770,
            _ => -1,
        };
        return protocol >= 0 && TryGetByProtocol(protocol, out version) || Fail(out version);
        static bool Fail(out JavaVersion v) { v = default!; return false; }
    }
}
