// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --out /tmp/gen --out-lang src/Umpk.Data.Lang
// </auto-generated>
#nullable enable

namespace Umpk.Data.Lang;

/// <summary>Generated vanilla-lang lookup. Pool is the deduplicated (key, template) pair table shared by every protocol; Index(protocol) is that protocol's own ascending, delta-packed list of pool positions, or an empty span for an unknown protocol. Mirrors the shape of Umpk.Data.Java.JavaGameData's per-protocol table switches (e.g. MenuDefs): a plain protocol -> blob switch, no per-version descriptor type.</summary>
internal static class JavaLanguage
{
    public static ReadOnlySpan<byte> Pool => LangTables.LanguagePoolShared;

    // Every protocol with a shipped table, ascending (indexMember is a SortedDictionary, so this and the Index(...) switch below are always built from the same order).
    public static ReadOnlySpan<int> Protocols => new int[] { 47, 107, 108, 109, 110, 210, 315, 316, 335, 338, 340, 393, 401, 404, 477, 480, 485, 490, 498, 573, 575, 578, 735, 736, 751, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776 };

    public static ReadOnlySpan<byte> Index(int protocol) => protocol switch
    {
        47 => LangTables.LanguageIndexV47,
        107 => LangTables.LanguageIndexV107,
        108 => LangTables.LanguageIndexV108,
        109 => LangTables.LanguageIndexV108,
        110 => LangTables.LanguageIndexV110,
        210 => LangTables.LanguageIndexV210,
        315 => LangTables.LanguageIndexV315,
        316 => LangTables.LanguageIndexV316,
        335 => LangTables.LanguageIndexV335,
        338 => LangTables.LanguageIndexV335,
        340 => LangTables.LanguageIndexV335,
        393 => LangTables.LanguageIndexV393,
        401 => LangTables.LanguageIndexV401,
        404 => LangTables.LanguageIndexV401,
        477 => LangTables.LanguageIndexV477,
        480 => LangTables.LanguageIndexV480,
        485 => LangTables.LanguageIndexV480,
        490 => LangTables.LanguageIndexV490,
        498 => LangTables.LanguageIndexV498,
        573 => LangTables.LanguageIndexV573,
        575 => LangTables.LanguageIndexV573,
        578 => LangTables.LanguageIndexV578,
        735 => LangTables.LanguageIndexV735,
        736 => LangTables.LanguageIndexV735,
        751 => LangTables.LanguageIndexV751,
        753 => LangTables.LanguageIndexV751,
        754 => LangTables.LanguageIndexV754,
        755 => LangTables.LanguageIndexV755,
        756 => LangTables.LanguageIndexV756,
        757 => LangTables.LanguageIndexV757,
        758 => LangTables.LanguageIndexV758,
        759 => LangTables.LanguageIndexV759,
        760 => LangTables.LanguageIndexV760,
        761 => LangTables.LanguageIndexV761,
        762 => LangTables.LanguageIndexV762,
        763 => LangTables.LanguageIndexV763,
        764 => LangTables.LanguageIndexV764,
        765 => LangTables.LanguageIndexV765,
        766 => LangTables.LanguageIndexV766,
        767 => LangTables.LanguageIndexV767,
        768 => LangTables.LanguageIndexV768,
        769 => LangTables.LanguageIndexV769,
        770 => LangTables.LanguageIndexV770,
        771 => LangTables.LanguageIndexV771,
        772 => LangTables.LanguageIndexV772,
        773 => LangTables.LanguageIndexV773,
        774 => LangTables.LanguageIndexV774,
        775 => LangTables.LanguageIndexV775,
        776 => LangTables.LanguageIndexV776,
        _ => default,
    };
}
