<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <!-- GameProfile -->
    <ProjectReference Include="../../src/Umpk.Core/Umpk.Core.csproj" />
    <!-- MinecraftAuthFlow, Yggdrasil interaction, session service -->
    <ProjectReference Include="../../src/Umpk.Auth/Umpk.Auth.csproj" />
  </ItemGroup>
</Project>
