<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Umpk.Nbt/Umpk.Nbt.csproj" />
    <ProjectReference Include="../../src/Umpk.Game/Umpk.Game.csproj" />
    <ProjectReference Include="../../src/Umpk.Protocol.Java/Umpk.Protocol.Java.csproj" />
    <ProjectReference Include="../../src/Umpk.Data.Java/Umpk.Data.Java.csproj" />
    <ProjectReference Include="../../src/Umpk.Physics/Umpk.Physics.csproj" />
    <ProjectReference Include="../../src/Umpk.Pathfinding/Umpk.Pathfinding.csproj" />
    <ProjectReference Include="../Umpk.TestKit/Umpk.TestKit.csproj" />
  </ItemGroup>
</Project>
