// <auto-generated>
// Generated by Umpk.DataGen from data/java. Do not edit by hand.
// Regenerate: dotnet run --project tools/Umpk.DataGen -- generate --data data/java --protocol-out src/Umpk.Protocol.Java
// </auto-generated>
#nullable enable

namespace Umpk.Protocol.Java.Codecs;

/// <summary>The per-era entity-metadata serializer tables: wire serializer id to value shape, in vanilla's own <c>EntityDataSerializers</c> registration order. An id resolved against the wrong era's table reads the wrong number of bytes and desynchronizes the rest of the metadata list.</summary>
internal sealed partial class ModernMetadataTable
{
    /// <summary>Protocol 107 (1.9) serializer order (ids 0-12).</summary>
    public static ModernMetadataTable V1_9 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 VARINT
        ModernMetadataSerializer.Float, // 2 FLOAT
        ModernMetadataSerializer.String, // 3 STRING
        ModernMetadataSerializer.Component, // 4 COMPONENT
        ModernMetadataSerializer.ItemStack, // 5 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 6 BOOLEAN
        ModernMetadataSerializer.Rotations, // 7 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 8 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 9 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 10 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 11 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 12 BLOCK_STATE
    ]);

    /// <summary>Protocol 335 (1.12) serializer order (ids 0-13).</summary>
    public static ModernMetadataTable V1_12 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 VARINT
        ModernMetadataSerializer.Float, // 2 FLOAT
        ModernMetadataSerializer.String, // 3 STRING
        ModernMetadataSerializer.Component, // 4 COMPONENT
        ModernMetadataSerializer.ItemStack, // 5 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 6 BOOLEAN
        ModernMetadataSerializer.Rotations, // 7 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 8 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 9 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 10 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 11 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 12 BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 13 COMPOUND_TAG
    ]);

    /// <summary>Protocol 393 (1.13) serializer order (ids 0-15).</summary>
    public static ModernMetadataTable V1_13 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Float, // 2 FLOAT
        ModernMetadataSerializer.String, // 3 STRING
        ModernMetadataSerializer.Component, // 4 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 5 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 6 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 7 BOOLEAN
        ModernMetadataSerializer.Rotations, // 8 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 9 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 10 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 11 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 12 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 13 BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 14 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 15 PARTICLE
    ]);

    /// <summary>Protocol 477 (1.14) serializer order (ids 0-18).</summary>
    public static ModernMetadataTable V1_14 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Float, // 2 FLOAT
        ModernMetadataSerializer.String, // 3 STRING
        ModernMetadataSerializer.Component, // 4 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 5 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 6 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 7 BOOLEAN
        ModernMetadataSerializer.Rotations, // 8 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 9 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 10 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 11 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 12 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 13 BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 14 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 15 PARTICLE
        ModernMetadataSerializer.VillagerData, // 16 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 17 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 18 POSE
    ]);

    /// <summary>Protocol 759 (1.19) serializer order (ids 0-22).</summary>
    public static ModernMetadataTable V1_19 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Float, // 2 FLOAT
        ModernMetadataSerializer.String, // 3 STRING
        ModernMetadataSerializer.Component, // 4 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 5 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 6 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 7 BOOLEAN
        ModernMetadataSerializer.Rotations, // 8 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 9 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 10 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 11 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 12 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 13 BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 14 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 15 PARTICLE
        ModernMetadataSerializer.VillagerData, // 16 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 17 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 18 POSE
        ModernMetadataSerializer.VarIntHolder, // 19 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 20 FROG_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 21 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 22 PAINTING_VARIANT
    ]);

    /// <summary>Protocol 761 (1.19.3) serializer order (ids 0-23).</summary>
    public static ModernMetadataTable V1_19_3 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 15 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 16 PARTICLE
        ModernMetadataSerializer.VillagerData, // 17 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 18 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 19 POSE
        ModernMetadataSerializer.VarIntHolder, // 20 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 21 FROG_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 22 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 23 PAINTING_VARIANT
    ]);

    /// <summary>Protocol 762 (1.19.4) serializer order (ids 0-27).</summary>
    public static ModernMetadataTable V1_19_4 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 16 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 17 PARTICLE
        ModernMetadataSerializer.VillagerData, // 18 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 19 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 20 POSE
        ModernMetadataSerializer.VarIntHolder, // 21 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 22 FROG_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 23 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 24 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 25 SNIFFER_STATE
        ModernMetadataSerializer.Vector3, // 26 VECTOR3
        ModernMetadataSerializer.Quaternion, // 27 QUATERNION
    ]);

    /// <summary>Protocol 766 (1.20.6) serializer order (ids 0-30).</summary>
    public static ModernMetadataTable V1_21_2 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_UUID
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 16 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 17 PARTICLE
        ModernMetadataSerializer.Particles, // 18 PARTICLES
        ModernMetadataSerializer.VillagerData, // 19 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 20 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 21 POSE
        ModernMetadataSerializer.VarIntHolder, // 22 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 23 WOLF_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 24 FROG_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 25 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 26 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 27 SNIFFER_STATE
        ModernMetadataSerializer.VarIntHolder, // 28 ARMADILLO_STATE
        ModernMetadataSerializer.Vector3, // 29 VECTOR3
        ModernMetadataSerializer.Quaternion, // 30 QUATERNION
    ]);

    /// <summary>Protocol 770 (1.21.5) serializer order (ids 0-34).</summary>
    public static ModernMetadataTable V1_21_5 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_LIVING_ENTITY_REFERENCE
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.CompoundTag, // 16 COMPOUND_TAG
        ModernMetadataSerializer.Particle, // 17 PARTICLE
        ModernMetadataSerializer.Particles, // 18 PARTICLES
        ModernMetadataSerializer.VillagerData, // 19 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 20 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 21 POSE
        ModernMetadataSerializer.VarIntHolder, // 22 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 23 COW_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 24 WOLF_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 25 WOLF_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 26 FROG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 27 PIG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 28 CHICKEN_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 29 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 30 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 31 SNIFFER_STATE
        ModernMetadataSerializer.VarIntHolder, // 32 ARMADILLO_STATE
        ModernMetadataSerializer.Vector3, // 33 VECTOR3
        ModernMetadataSerializer.Quaternion, // 34 QUATERNION
    ]);

    /// <summary>Protocol 773 (1.21.10) serializer order (ids 0-36).</summary>
    public static ModernMetadataTable V1_21_9 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_LIVING_ENTITY_REFERENCE
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.Particle, // 16 PARTICLE
        ModernMetadataSerializer.Particles, // 17 PARTICLES
        ModernMetadataSerializer.VillagerData, // 18 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 19 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 20 POSE
        ModernMetadataSerializer.VarIntHolder, // 21 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 22 COW_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 23 WOLF_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 24 WOLF_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 25 FROG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 26 PIG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 27 CHICKEN_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 28 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 29 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 30 SNIFFER_STATE
        ModernMetadataSerializer.VarIntHolder, // 31 ARMADILLO_STATE
        ModernMetadataSerializer.VarIntHolder, // 32 COPPER_GOLEM_STATE
        ModernMetadataSerializer.VarIntHolder, // 33 WEATHERING_COPPER_STATE
        ModernMetadataSerializer.Vector3, // 34 VECTOR3
        ModernMetadataSerializer.Quaternion, // 35 QUATERNION
        ModernMetadataSerializer.ResolvableProfile, // 36 RESOLVABLE_PROFILE
    ]);

    /// <summary>Protocol 774 (1.21.11) serializer order (ids 0-38).</summary>
    public static ModernMetadataTable V1_21_11 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_LIVING_ENTITY_REFERENCE
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.Particle, // 16 PARTICLE
        ModernMetadataSerializer.Particles, // 17 PARTICLES
        ModernMetadataSerializer.VillagerData, // 18 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 19 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 20 POSE
        ModernMetadataSerializer.VarIntHolder, // 21 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 22 COW_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 23 WOLF_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 24 WOLF_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 25 FROG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 26 PIG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 27 CHICKEN_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 28 ZOMBIE_NAUTILUS_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 29 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 30 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 31 SNIFFER_STATE
        ModernMetadataSerializer.VarIntHolder, // 32 ARMADILLO_STATE
        ModernMetadataSerializer.VarIntHolder, // 33 COPPER_GOLEM_STATE
        ModernMetadataSerializer.VarIntHolder, // 34 WEATHERING_COPPER_STATE
        ModernMetadataSerializer.Vector3, // 35 VECTOR3
        ModernMetadataSerializer.Quaternion, // 36 QUATERNION
        ModernMetadataSerializer.ResolvableProfile, // 37 RESOLVABLE_PROFILE
        ModernMetadataSerializer.VarIntHolder, // 38 HUMANOID_ARM
    ]);

    /// <summary>Protocol 775 (26.1) serializer order (ids 0-42).</summary>
    public static ModernMetadataTable V26_1 { get; } = new(
    [
        ModernMetadataSerializer.Byte, // 0 BYTE
        ModernMetadataSerializer.Int, // 1 INT
        ModernMetadataSerializer.Long, // 2 LONG
        ModernMetadataSerializer.Float, // 3 FLOAT
        ModernMetadataSerializer.String, // 4 STRING
        ModernMetadataSerializer.Component, // 5 COMPONENT
        ModernMetadataSerializer.OptionalComponent, // 6 OPTIONAL_COMPONENT
        ModernMetadataSerializer.ItemStack, // 7 ITEM_STACK
        ModernMetadataSerializer.Boolean, // 8 BOOLEAN
        ModernMetadataSerializer.Rotations, // 9 ROTATIONS
        ModernMetadataSerializer.BlockPos, // 10 BLOCK_POS
        ModernMetadataSerializer.OptionalBlockPos, // 11 OPTIONAL_BLOCK_POS
        ModernMetadataSerializer.Direction, // 12 DIRECTION
        ModernMetadataSerializer.OptionalUuid, // 13 OPTIONAL_LIVING_ENTITY_REFERENCE
        ModernMetadataSerializer.BlockState, // 14 BLOCK_STATE
        ModernMetadataSerializer.OptionalBlockState, // 15 OPTIONAL_BLOCK_STATE
        ModernMetadataSerializer.Particle, // 16 PARTICLE
        ModernMetadataSerializer.Particles, // 17 PARTICLES
        ModernMetadataSerializer.VillagerData, // 18 VILLAGER_DATA
        ModernMetadataSerializer.OptionalUnsignedInt, // 19 OPTIONAL_UNSIGNED_INT
        ModernMetadataSerializer.Pose, // 20 POSE
        ModernMetadataSerializer.VarIntHolder, // 21 CAT_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 22 CAT_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 23 COW_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 24 COW_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 25 WOLF_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 26 WOLF_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 27 FROG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 28 PIG_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 29 PIG_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 30 CHICKEN_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 31 CHICKEN_SOUND_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 32 ZOMBIE_NAUTILUS_VARIANT
        ModernMetadataSerializer.OptionalGlobalPos, // 33 OPTIONAL_GLOBAL_POS
        ModernMetadataSerializer.VarIntHolder, // 34 PAINTING_VARIANT
        ModernMetadataSerializer.VarIntHolder, // 35 SNIFFER_STATE
        ModernMetadataSerializer.VarIntHolder, // 36 ARMADILLO_STATE
        ModernMetadataSerializer.VarIntHolder, // 37 COPPER_GOLEM_STATE
        ModernMetadataSerializer.VarIntHolder, // 38 WEATHERING_COPPER_STATE
        ModernMetadataSerializer.Vector3, // 39 VECTOR3
        ModernMetadataSerializer.Quaternion, // 40 QUATERNION
        ModernMetadataSerializer.ResolvableProfile, // 41 RESOLVABLE_PROFILE
        ModernMetadataSerializer.VarIntHolder, // 42 HUMANOID_ARM
    ]);
}
